<?php

include('includes/kp_fields.mviews.inc');

/**
 * Implements hook_bundle_create_user_field().
 *
 * We use this hook to ensure mviews are created only as the fields that need 
 * them are created.
 *
 * @untested
 *
function kp_fields_bundle_create_user_field($new_field, $bundle) {

  // Some fields need materialized views.
  // Thus depending on the field, we will add the materialized view.
  // This way if a field is never created you don't have the mviews cluttering up your instance.
  include(drupal_get_path('module','kp_fields') . '/includes/kp_fields.mviews.inc');
  if ($new_field['type'] == 'organism_counts') {
    $mview = kp_fields_organism_counts_mview();
    tripal_add_mview($mview['name'], $mview['module_name'], $mview['mv_schema'], $mview['query']);
  }

  // Create the field.
  $field = array(
    'field_name' => $new_field['field_name'],
    'type' => $new_field['type'],
    'cardinality' => FIELD_CARDINALITY_UNLIMITED, // @hard-coded
    'locked' => FALSE,
    'storage' => array(
      'type' => $type::$default_settings['storage']
    ),
  );
  field_create_field($field);

  // Then create the instance.
  $instance =  array(
    'field_name' => $new_field['field_name'],
    'entity_type' => $bundle->type,
    'bundle' => $bundle->name,
    'label' => $new_field['label'],
    'description' => $type::$default_description,
    'required' => FALSE,
    'settings' => array(
      'auto_attach' => $type::$default_instance_settings['auto_attach'],
    ),
    'widget' => array(
      'type' => $new_field['widget_type'],
      'settings' => array(),
    ),
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'type' => $type::$default_formatter,
        'settings' => array(),
      ),
    ),
  );
  field_create_instance($instance);

}
*/
